#!/usr/bin/env python3
"""Parse workload benchmark logs into CSV files.

Parses benchmark logs generated by `./syclgen/remote_run.sh -t workload`
and extracts per-run performance data into CSV format.

Usage:
    python3 syclgen/parse_workload_logs.py <log_file> [<log_file> ...]
"""

import csv
import os
import re
import sys

# ANSI escape code pattern for stripping color codes
ANSI_RE = re.compile(r"\x1b\[[0-9;]*m")


def strip_ansi(text: str) -> str:
    return ANSI_RE.sub("", text)


def parse_workload_log(log_path: str) -> list[dict]:
    """Parse a single workload benchmark log file.

    Returns a list of dicts with keys:
        Model, Input Length, Output Length, Batch Size,
        Prefill Throughput (token/s), Decode Throughput (token/s)
    """
    rows = []
    current_model = None
    current_p = None
    current_n = None
    current_ub = None
    prefill_tp = None
    decode_tp = None

    def flush_run():
        """Save the current pending run if both prefill and decode are available."""
        nonlocal prefill_tp, decode_tp
        if prefill_tp is not None and decode_tp is not None:
            rows.append({
                "Model": current_model,
                "Input Length": current_p,
                "Output Length": current_n,
                "Batch Size": current_ub,
                "Prefill Throughput (token/s)": prefill_tp,
                "Decode Throughput (token/s)": decode_tp,
            })
        prefill_tp = None
        decode_tp = None

    with open(log_path, "r") as f:
        for raw_line in f:
            line = strip_ansi(raw_line).strip()

            # Match model announcement: [INFO] Model: Qwen3-0.6B-Q8_0.gguf
            m = re.match(r"\[INFO\]\s+Model:\s+(.+)", line)
            if m:
                # Flush any pending run from the previous model
                flush_run()
                current_model = m.group(1).strip()
                continue

            # Match run config: [INFO] [N] p=128 n=32 ub=16
            m = re.match(r"\[INFO\]\s+\[\d+\]\s+p=(\d+)\s+n=(\d+)\s+ub=(\d+)", line)
            if m:
                # Save previous run if complete
                flush_run()
                current_p = int(m.group(1))
                current_n = int(m.group(2))
                current_ub = int(m.group(3))
                continue

            # Match data rows from the pipe-separated table.
            # Example lines (with or without n_ubatch column):
            #   | qwen3 0.6B Q8_0  | 604.15 MiB | 596.05 M | SYCL | 99 | 16 | pp128 | 826.16 ± 3.89 |
            #   | qwen3 14B Q8_0   | 14.61 GiB  | 14.77 B  | SYCL | 99 |      pp2048 | 1113.47 ± 0.68 |
            if line.startswith("|") and current_model is not None:
                cells = [c.strip() for c in line.split("|")]
                # cells[0] and cells[-1] are empty strings from leading/trailing pipes

                # Find the test column (ppXXX or tgXX) and throughput column
                # The test value is always second-to-last non-empty cell,
                # throughput is always the last non-empty cell.
                non_empty = [c for c in cells if c and not c.startswith("-")]
                if len(non_empty) < 2:
                    continue

                test_val = non_empty[-2].strip()
                tp_val = non_empty[-1].strip()

                # Skip header row
                if test_val == "test" or test_val == "t/s":
                    continue

                # Extract throughput number (e.g., "826.16 ± 3.89" -> 826.16)
                tp_match = re.match(r"([\d.]+)", tp_val)
                if not tp_match:
                    continue
                tp = float(tp_match.group(1))

                if test_val.startswith("pp"):
                    prefill_tp = tp
                elif test_val.startswith("tg"):
                    decode_tp = tp

    # Don't forget the last run
    flush_run()

    return rows


def write_csv(rows: list[dict], csv_path: str) -> None:
    """Write parsed rows to a CSV file."""
    fieldnames = [
        "Model",
        "Input Length",
        "Output Length",
        "Batch Size",
        "Prefill Throughput (token/s)",
        "Decode Throughput (token/s)",
    ]
    with open(csv_path, "w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)


def main():
    if len(sys.argv) < 2:
        print(f"Usage: {sys.argv[0]} <log_file> [<log_file> ...]", file=sys.stderr)
        sys.exit(1)

    for log_path in sys.argv[1:]:
        if not os.path.isfile(log_path):
            print(f"ERROR: File not found: {log_path}", file=sys.stderr)
            continue

        rows = parse_workload_log(log_path)
        csv_path = os.path.splitext(log_path)[0] + ".csv"
        write_csv(rows, csv_path)
        print(f"Parsed {len(rows)} runs from {log_path} -> {csv_path}")


if __name__ == "__main__":
    main()
