#!/usr/bin/env python3
#==============================================================
# Annotate a .asm.ip file (generated by analyzeperfmetrics.py)
# with per-instruction stall metrics looked up by IP from the
# stall-sampling metrics CSV produced by `unitrace --stall-sampling`.
#
# For every instruction line in the .asm.ip file of the form
#     /* [0000A1B0] */ <instruction> ...
# the matching IP row in the CSV is found and its stall metrics are
# emitted as a comment line placed immediately above the instruction, e.g.
#     // [STALL] Active=12 PipeStall=3 ...
#     /* [0000A1B0] */ <instruction> ...
#==============================================================

import argparse
import csv
import os
import re
import subprocess
import sys

# Metrics to annotate, in the order requested. The CSV column name is
# "<NAME>[Events]". Only metrics actually present in the CSV are emitted.
METRIC_NAMES = [
    "Active",
    "PSDepStall",
    "ControlStall",
    "PipeStall",
    "SendStall",
    "DistStall",
    "SbidStall",
    "SyncStall",
    "InstrFetchStall",
    "OtherStall",
]

# Match an instruction line that carries an IP address: "/* [0000A1B0] */ ..."
IP_LINE_RE = re.compile(r"^/\*\s*\[([0-9A-Fa-f]+)\]\s*\*/")


def demangle(name):
    """Demangle a symbol with c++filt, mirroring analyzeperfmetrics.py.

    Returns the original name unchanged if c++filt is unavailable.
    """
    try:
        p = subprocess.Popen(["c++filt", name], stdin=subprocess.PIPE,
                             stdout=subprocess.PIPE, text=True)
        stdout, _ = p.communicate()
        demangled = stdout.split("\n")[0]
        if "typeinfo name for" not in demangled:  # name is not mangled
            return name
        return demangled[18:]  # skip leading "typeinfo name for "
    except (FileNotFoundError, PermissionError, subprocess.SubprocessError):
        return name


def select_asm_ip_file(shaderdump, kernel):
    """Select the single .asm.ip file for the kernel from the shader dump.

    Mirrors analyzeperfmetrics.py AnalyzeStalls(): match files by the
    `//.kernel` line (demangled), and when more than one matches, pick the
    one with the longest file name, breaking ties by largest name in
    alphabetical order (the latest retried compilation). Returns the path,
    or None if no matching .asm.ip file is found.
    """
    if not os.path.isdir(shaderdump):
        return None

    files = [
        os.path.join(shaderdump, f)
        for f in sorted(os.listdir(shaderdump))
        if f.endswith(".asm.ip")
    ]
    if not files:
        return None

    asmfiles = []
    for f in files:
        with open(f, "r") as inf:
            for row in inf:
                if row.startswith("//.kernel"):
                    parts = row.split()
                    if len(parts) < 2:
                        break
                    kname = demangle(parts[1])
                    if kernel is None or kernel == kname:
                        asmfiles.append(f)
                    break

    # Fall back to all .asm.ip files if none matched the kernel name (e.g. the
    # `//.kernel` line is absent or uses a different naming convention).
    if not asmfiles:
        if kernel is not None:
            print(f"annotate_asm_stalls: no .asm.ip file for kernel '{kernel}'")
            return None
        asmfiles = files

    asm = asmfiles[0]
    if len(asmfiles) > 1:  # kernel has been retried, find the latest one
        # The latest one has the longest file name.
        max_len = 0
        for f in asmfiles:
            if len(f) > max_len:
                max_len = len(f)
                asm = f
        # Among the longest, the latest is the largest in alphabetical order.
        for f in asmfiles:
            if len(f) == max_len and asm < f:
                asm = f

    return asm



def parse_stall_csv(csv_path, device):
    """Parse the stall-sampling CSV and return a mapping:

        { kernel_name: { ip_int: {metric_name: value, ...}, ... }, ... }

    The CSV groups rows by device (banner "=== Device #N Metrics ===")
    followed by a header line starting with "Kernel," that contains the
    stall columns, then one data row per sampled IP.
    """
    device_banner = "=== Device #" + str(device) + " Metrics ==="

    header_fields = None
    data_lines = []
    in_device = False
    device_found = False

    with open(csv_path, "r", newline="") as f:
        for raw in f:
            if ("=== Device" in raw) and ("Metrics ===" in raw):
                if device_banner in raw:
                    in_device = True
                    device_found = True
                elif device_found:
                    # Reached the next device section; we are done.
                    break
                continue
            if not in_device:
                continue
            if header_fields is None:
                if "OtherStall[Events]" in raw and "Kernel" in raw:
                    header_fields = [
                        c.strip() for c in next(csv.reader([raw.strip()]))
                    ]
                continue
            # Collect data rows until a blank line ends the section.
            if raw.strip() == "":
                continue
            data_lines.append(raw)

    if not device_found:
        print(f"annotate_asm_stalls: device {device} not found in {csv_path}")
        return {}
    if header_fields is None:
        print(f"annotate_asm_stalls: no stall header found in {csv_path}")
        return {}

    col_index = {name: i for i, name in enumerate(header_fields)}
    if "Kernel" not in col_index or "IP[Address]" not in col_index:
        print(f"annotate_asm_stalls: missing Kernel/IP columns in {csv_path}")
        return {}

    kernel_idx = col_index["Kernel"]
    ip_idx = col_index["IP[Address]"]
    metric_cols = [
        (name, col_index[name + "[Events]"])
        for name in METRIC_NAMES
        if (name + "[Events]") in col_index
    ]

    result = {}
    for row in csv.reader(data_lines):
        if len(row) <= max(kernel_idx, ip_idx):
            continue
        kernel = row[kernel_idx].strip().strip('"')
        ip_str = row[ip_idx].strip()
        if not ip_str:
            continue
        try:
            ip = int(ip_str, 16) if ip_str.lower().startswith("0x") else int(ip_str, 16)
        except ValueError:
            continue

        metrics = {}
        for name, idx in metric_cols:
            if idx >= len(row):
                continue
            val = row[idx].strip()
            try:
                metrics[name] = int(float(val))
            except ValueError:
                continue

        per_kernel = result.setdefault(kernel, {})
        existing = per_kernel.get(ip)
        if existing is None:
            per_kernel[ip] = metrics
        else:
            for name, val in metrics.items():
                existing[name] = existing.get(name, 0) + val

    return result


def select_ip_map(kernel_maps, kernel):
    """Pick the IP->metrics map for the requested kernel.

    Falls back to substring matching and finally to merging all kernels
    when no exact match is found.
    """
    if not kernel_maps:
        return {}
    if kernel:
        if kernel in kernel_maps:
            return kernel_maps[kernel]
        matches = [k for k in kernel_maps if kernel in k]
        if len(matches) == 1:
            return kernel_maps[matches[0]]
        if len(matches) > 1:
            print(f"annotate_asm_stalls: '{kernel}' matches multiple kernels; merging all")
    # Merge all kernels' IP maps.
    if len(kernel_maps) == 1:
        return next(iter(kernel_maps.values()))
    merged = {}
    for per_kernel in kernel_maps.values():
        for ip, metrics in per_kernel.items():
            dst = merged.setdefault(ip, {})
            for name, val in metrics.items():
                dst[name] = dst.get(name, 0) + val
    return merged


def compute_top_ranks(ip_map, topn=10):
    """Return {metric_name: {ip: rank}} for the top-N IPs of each metric.

    For every metric, IPs are ranked by descending value (only values > 0
    are considered) and the top `topn` get a 1-based rank.
    """
    ranks = {}
    for name in METRIC_NAMES:
        scored = [
            (ip, metrics[name])
            for ip, metrics in ip_map.items()
            if metrics.get(name, 0) > 0
        ]
        scored.sort(key=lambda kv: kv[1], reverse=True)
        ranks[name] = {ip: i + 1 for i, (ip, _) in enumerate(scored[:topn])}
    return ranks


def annotate_file(asm_path, ip_map, output_path, top_ranks=None):
    """Write an annotated copy of asm_path to output_path.

    The stall metrics for an instruction are emitted as a comment line
    placed immediately above the corresponding instruction. If any metric
    value for the instruction is in the top-N ranking for that metric, a
    trailing note like `*** SbidStall top 1 ***` is appended.
    """
    top_ranks = top_ranks or {}
    annotated = 0
    with open(asm_path, "r") as inf, open(output_path, "w") as outf:
        for line in inf:
            newline = "\n" if line.endswith("\n") else ""
            body = line[:-1] if newline else line
            m = IP_LINE_RE.match(body)
            if m:
                ip = int(m.group(1), 16)
                metrics = ip_map.get(ip)
                if metrics:
                    parts = [
                        f"{name}={metrics[name]}"
                        for name in METRIC_NAMES
                        if name in metrics
                    ]
                    if parts:
                        indent = body[:len(body) - len(body.lstrip())]
                        comment = indent + "// [STALL] " + " ".join(parts)
                        notes = [
                            f"{name} top {top_ranks[name][ip]}"
                            for name in METRIC_NAMES
                            if ip in top_ranks.get(name, {})
                        ]
                        if notes:
                            comment += " // *** " + " *** ".join(notes) + " ***"
                        outf.write(comment + "\n")
                        annotated += 1
            outf.write(body + newline)
    return annotated


def main(argv):
    parser = argparse.ArgumentParser(
        description="Annotate .asm.ip files with per-instruction stall metrics by IP")
    parser.add_argument("csv", help="stall-sampling metrics CSV (unitrace --stall-sampling)")
    parser.add_argument("-s", "--shaderdump",
                        help="shader dump folder containing the .asm.ip file(s)")
    parser.add_argument("-a", "--asm",
                        help="explicit path to a single .asm.ip file (overrides -s)")
    parser.add_argument("-k", "--kernel",
                        help="kernel name to select rows from the CSV")
    parser.add_argument("-d", "--device", type=int, default=0,
                        help="GPU device index in the CSV (default 0)")
    parser.add_argument("-o", "--output",
                        help="output file path (default <asm.ip>.stall)")
    args = parser.parse_args(argv)

    if not os.path.isfile(args.csv):
        print(f"annotate_asm_stalls: CSV not found: {args.csv}")
        return 1

    if args.asm:
        asm_files = [args.asm] if os.path.isfile(args.asm) else []
    else:
        if not args.shaderdump:
            print("annotate_asm_stalls: provide -a <asm.ip> or -s <shaderdump>")
            return 1
        asm = select_asm_ip_file(args.shaderdump, args.kernel)
        asm_files = [asm] if asm else []

    if not asm_files:
        # Requirement: if no .asm.ip file is found, do nothing.
        print("annotate_asm_stalls: no .asm.ip file found, nothing to do")
        return 0

    kernel_maps = parse_stall_csv(args.csv, args.device)
    if not kernel_maps:
        print("annotate_asm_stalls: no stall metrics parsed from CSV, nothing to do")
        return 0

    ip_map = select_ip_map(kernel_maps, args.kernel)
    if not ip_map:
        print("annotate_asm_stalls: no matching stall metrics for kernel, nothing to do")
        return 0

    top_ranks = compute_top_ranks(ip_map, topn=10)
    for asm in asm_files:
        out = args.output if args.output else asm + ".stall"
        count = annotate_file(asm, ip_map, out, top_ranks)
        print(f"annotate_asm_stalls: annotated {count} instructions -> {out}")

    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
