#!/usr/bin/env bash
# Regenerate .sycl/PROGRESS.md from the structured JSON state under .sycl/state/.
# PROGRESS.md is a GENERATED VIEW — never hand-edit it; edit the JSON and re-run this.
# Called by the agent after every state change so the human view never drifts from state.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SYCL_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"   # .sycl/

python3 - "$SYCL_DIR" <<'PY'
import json, os, sys, datetime

sycl = sys.argv[1]
state = os.path.join(sycl, "state")

def load(path, default=None):
    try:
        with open(path) as f:
            return json.load(f)
    except (FileNotFoundError, json.JSONDecodeError):
        return default

project = load(os.path.join(state, "project.json"), {}) or {}
index   = load(os.path.join(state, "kernels", "index.json"), {}) or {}
e2e     = load(os.path.join(state, "profile", "e2e.json"), {}) or {}
metrics = load(os.path.join(state, "metrics.json"), {}) or {}

kernels = index.get("kernels", [])
by_id = {k.get("id"): k for k in kernels}

def load_detail(kid):
    return load(os.path.join(state, "kernels", f"{kid}.json"), {}) or {}

# --- counts ---
total   = len(kernels)
def count(status): return sum(1 for k in kernels if k.get("status") == status)
migrated = count("migrated")
skipped  = count("skipped")
pending  = count("pending")
needsref = count("needs-reference")
optimized = sum(1 for k in kernels if load_detail(k.get("id")).get("optimization", {}).get("status") == "done")

now = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

# --- heartbeat + history (independent cross-check of metrics.json timing) ---
# gen-progress runs after every state change -- far more reliably than the agent remembers to call
# metrics.sh start/stop. So we append one timestamped snapshot per run to an append-only trail; its
# span is a trustworthy LOWER BOUND on real wall-clock even when metrics.sh was never called, and the
# trail doubles as a kept history of how the run progressed. (rotate-logs.sh only rotates *.log, so
# this *.jsonl keeps its earliest anchor.)
logdir = os.path.join(sycl, "logs")
os.makedirs(logdir, exist_ok=True)
hist_path = os.path.join(logdir, "progress.jsonl")
snapshot = {"ts": now, "phase": project.get("phase", "?"), "total": total,
            "migrated": migrated, "optimized": optimized, "skipped": skipped,
            "needs_reference": needsref, "pending": pending}
try:
    with open(hist_path, "a") as hf:
        hf.write(json.dumps(snapshot) + "\n")
except OSError:
    pass

def _parse_ts(ts):
    try:
        return datetime.datetime.strptime(ts, "%Y-%m-%dT%H:%M:%SZ").replace(tzinfo=datetime.timezone.utc)
    except Exception:
        return None

beats = []
if os.path.exists(hist_path):
    with open(hist_path) as hf:
        for ln in hf:
            ln = ln.strip()
            if not ln:
                continue
            try:
                r = json.loads(ln)
            except json.JSONDecodeError:
                continue
            d = _parse_ts(r.get("ts", ""))
            if d is not None:
                beats.append((d, r))
beats.sort(key=lambda x: x[0])

# Gaps longer than IDLE_CAP are treated as idle (overnight, waiting on the human), not working time,
# so `observed_work` is a robust proxy for real agent time that survives long pauses between sessions.
IDLE_CAP = int(os.environ.get("SYCL_PROGRESS_IDLE_CAP", "1800"))
observed_span = observed_work = 0
if beats:
    observed_span = int((beats[-1][0] - beats[0][0]).total_seconds())
    for (a, _ra), (b, _rb) in zip(beats, beats[1:]):
        gap = int((b - a).total_seconds())
        observed_work += min(max(gap, 0), IDLE_CAP)

lines = []
lines.append("<!-- GENERATED by .sycl/scripts/gen-progress.sh — DO NOT EDIT. Edit state/*.json instead. -->")
lines.append(f"# Migration Progress — {project.get('name','(unknown project)')}")
lines.append("")
env = project.get("env", {})
runner = project.get("runner_mode", "local")
lines.append(
    f"- **Runner**: {runner}"
    + (f" ({project.get('runner_host')})" if project.get('runner_host') else "")
)
lines.append(f"- **Toolchain**: {env.get('icpx','?')}  ·  **GPU**: {env.get('gpu','?')} "
             f"({env.get('arch','?')})  ·  **oneAPI**: {env.get('oneapi','?')}")
lines.append(f"- **Benchmark GPU freq pinned**: {env.get('freq_pinned','?')}")
lines.append(f"- **Build system**: {project.get('build_system','?')} → SYCL build: {project.get('sycl_build','?')}")
lines.append(f"- **Phase**: {project.get('phase','?')}")
lines.append(f"- **Updated**: {now}")
lines.append("")
lines.append(f"**Summary**: {total} kernels — {migrated} migrated, {optimized} optimized, "
             f"{skipped} skipped, {needsref} needs-reference, {pending} pending.")
lines.append("")

# --- kernel table ---
lines.append("## Kernels")
lines.append("")
lines.append("| id | source | status | unit test | impact % | baseline | optimized | notes |")
lines.append("|----|--------|--------|-----------|----------|----------|-----------|-------|")
impact = {r.get("id"): r.get("wallclock_pct") for r in e2e.get("ranking", [])}
# order by impact desc when available, else index order
def sort_key(k):
    p = impact.get(k.get("id"))
    return (-(p if isinstance(p, (int, float)) else -1),)
for k in sorted(kernels, key=sort_key):
    kid = k.get("id", "?")
    d = load_detail(kid)
    perf = d.get("performance", {})
    ut = d.get("unit_test", {})
    ut_s = ut.get("result", "-")
    if ut.get("tolerance"):
        ut_s = f"{ut_s} ({ut['tolerance']})"
    imp = impact.get(kid)
    imp_s = f"{imp:.1f}" if isinstance(imp, (int, float)) else "-"
    lines.append("| {id} | {src} | {status} | {ut} | {imp} | {base} | {opt} | {notes} |".format(
        id=kid,
        src=k.get("source", "-"),
        status=k.get("status", "-"),
        ut=ut_s,
        imp=imp_s,
        base=perf.get("baseline", "-"),
        opt=perf.get("optimized", "-"),
        notes=(k.get("notes") or d.get("notes") or "-"),
    ))
lines.append("")

# --- analytics: agent efficiency & cost, with an independent heartbeat cross-check ---
def hms(s):
    s = int(s or 0); h = s // 3600; mnt = (s % 3600) // 60; sec = s % 60
    if h:   return f"{h}h{mnt:02d}m{sec:02d}s"
    if mnt: return f"{mnt}m{sec:02d}s"
    return f"{sec}s"

tot    = (metrics or {}).get("totals", {})
sess   = (metrics or {}).get("session", {})
phases = (metrics or {}).get("phases", {})
active = {p: b for p, b in phases.items() if any((b or {}).values())}

lines.append("## Agent efficiency & cost")
lines.append("")
if metrics:
    lines.append(
        f"- **Elapsed**: {hms(sess.get('elapsed_wall_seconds'))} (whole run)  ·  "
        f"**Active**: {hms(sess.get('active_wall_seconds', tot.get('wall_clock_seconds')))} (bracketed)  ·  "
        f"**Cost**: ${tot.get('cost_usd', 0)}  ·  "
        f"**Tokens**: {tot.get('tokens_total', 0)} "
        f"(in {tot.get('tokens_in', 0)} / out {tot.get('tokens_out', 0)} / "
        f"cache r {tot.get('cache_read', 0)} / cache w {tot.get('cache_write', 0)})  ·  "
        f"**Premium requests**: {tot.get('requests', 0)}  ·  "
        f"**AI credits**: {tot.get('credits', 0)}"
    )
# Independent cross-check from the gen-progress heartbeat (does NOT depend on metrics.sh start/stop).
if beats:
    lines.append(
        f"- **Observed (gen-progress heartbeat)**: span {hms(observed_span)}  ·  "
        f"working ≈ {hms(observed_work)} (idle-capped {hms(IDLE_CAP)})  ·  "
        f"{len(beats)} snapshots — independent of metrics.sh"
    )
    sess_active = int(sess.get('active_wall_seconds', tot.get('wall_clock_seconds', 0)) or 0)
    if metrics and observed_work and sess_active < 0.5 * observed_work:
        lines.append(
            f"  - ⚠️ bracketed active time ({hms(sess_active)}) is far below observed work "
            f"({hms(observed_work)}); phases were under-bracketed — trust elapsed/observed figures."
        )
lines.append("")
if metrics and active:
    lines.append("| phase | elapsed | active | tokens | requests | credits | USD |")
    lines.append("|-------|--------:|-------:|-------:|---------:|--------:|----:|")
    for p, b in active.items():
        lines.append("| {p} | {el} | {t} | {tok} | {req} | {cr} | {usd} |".format(
            p=p, el=hms(b.get("elapsed_wall_seconds")), t=hms(b.get("wall_clock_seconds")),
            tok=b.get("tokens_total", 0), req=b.get("requests", 0),
            cr=b.get("credits", 0), usd=b.get("cost_usd", 0),
        ))
    lines.append("")

# --- progress history (append-only heartbeat trail; kept across the whole run) ---
if len(beats) > 1:
    lines.append("## Progress history")
    lines.append("")
    lines.append("<!-- append-only from logs/progress.jsonl — one row per gen-progress run -->")
    lines.append("| time (UTC) | phase | migrated | optimized | skipped | pending |")
    lines.append("|------------|-------|---------:|----------:|--------:|--------:|")
    for d, r in beats[-12:]:
        lines.append("| {ts} | {ph} | {m}/{tot} | {o} | {s} | {p} |".format(
            ts=r.get("ts", "?"), ph=r.get("phase", "?"),
            m=r.get("migrated", 0), tot=r.get("total", 0),
            o=r.get("optimized", 0), s=r.get("skipped", 0), p=r.get("pending", 0)))
    lines.append("")

# --- lessons (from sycl-reference lessons file if present) ---
lessons = os.path.join(sycl, "state", "lessons.md")
if os.path.exists(lessons):
    lines.append("## Lessons")
    lines.append("")
    with open(lessons) as f:
        lines.append(f.read().rstrip())
    lines.append("")

with open(os.path.join(sycl, "PROGRESS.md"), "w") as f:
    f.write("\n".join(lines) + "\n")
print("wrote", os.path.join(sycl, "PROGRESS.md"))
PY
