#!/usr/bin/env bash
# Initialize .sycl runtime state from templates (idempotent: never overwrites existing state).
# Usage: init-state.sh [project_name]
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SYCL_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"      # .sycl/
TEMPLATES="$SYCL_DIR/templates"
STATE="$SYCL_DIR/state"
PROJECT_NAME="${1:-$(basename "$(cd "$SYCL_DIR/.." && pwd)")}"

mkdir -p "$STATE/kernels" "$STATE/profile" "$STATE/optimization" "$STATE/integration" \
         "$SYCL_DIR/reports" "$SYCL_DIR/logs" \
         "$SYCL_DIR/reports/evidence/env" "$SYCL_DIR/reports/evidence/test" \
         "$SYCL_DIR/reports/evidence/bench" "$SYCL_DIR/reports/evidence/e2e" \
         "$SYCL_DIR/reports/evidence/build" "$SYCL_DIR/reports/evidence/integration"

now="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

copy_if_absent() {
  local src="$1" dst="$2"
  if [[ -f "$dst" ]]; then
    echo "exists, kept: ${dst#"$SYCL_DIR"/}"
  else
    cp "$src" "$dst"
    echo "created: ${dst#"$SYCL_DIR"/}"
  fi
}

# config.json (runner + toolchain) lives at .sycl/config.json
copy_if_absent "$TEMPLATES/config.json"        "$SYCL_DIR/config.json"
# structured state
copy_if_absent "$TEMPLATES/project.json"       "$STATE/project.json"
copy_if_absent "$TEMPLATES/kernel-index.json"  "$STATE/kernels/index.json"
# last-mile backend integration: the surfaces to close, and the readiness ladder they unlock.
copy_if_absent "$TEMPLATES/integration-index.json"      "$STATE/integration/index.json"
copy_if_absent "$TEMPLATES/integration-readiness.json"  "$STATE/integration/readiness.json"
# the phase-exit contract: each phase's completion criteria, the gate log, and the frozen
# work-item denominator. Without this file `evidence.sh gate` has nothing to write to and a
# phase can be left simply by not asking (checks E15/E16/E17).
copy_if_absent "$TEMPLATES/phases.json"        "$STATE/phases.json"
# analytics rollup (efficiency & cost); regenerated by metrics.sh, seeded here so the
# dashboard/report always have a file to read.
copy_if_absent "$TEMPLATES/metrics.json"       "$STATE/metrics.json"

# Stamp project name + timestamp into a freshly created project.json (best-effort, no jq dep).
if grep -q '"name": "REPLACE_ME"' "$STATE/project.json" 2>/dev/null; then
  sed -i.bak \
    -e "s/\"name\": \"REPLACE_ME\"/\"name\": \"${PROJECT_NAME//\//\\/}\"/" \
    -e "s/\"updated_at\": \"1970-01-01T00:00:00Z\"/\"updated_at\": \"${now}\"/" \
    "$STATE/project.json" && rm -f "$STATE/project.json.bak"
  echo "stamped project name: $PROJECT_NAME"
fi

# Generate the initial PROGRESS.md view.
bash "$SCRIPT_DIR/gen-progress.sh" >/dev/null 2>&1 || true

echo "State initialized under: $SYCL_DIR"
