#!/usr/bin/env bash
# Initialize .sycl runtime state from templates (idempotent: never overwrites existing state).
# Usage: init-state.sh [project_name]
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SYCL_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"      # .sycl/
TEMPLATES="$SYCL_DIR/templates"
STATE="$SYCL_DIR/state"
PROJECT_NAME="${1:-$(basename "$(cd "$SYCL_DIR/.." && pwd)")}"

mkdir -p "$STATE/kernels" "$STATE/profile" "$STATE/optimization" \
         "$SYCL_DIR/reports" "$SYCL_DIR/logs"

now="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

copy_if_absent() {
  local src="$1" dst="$2"
  if [[ -f "$dst" ]]; then
    echo "exists, kept: ${dst#"$SYCL_DIR"/}"
  else
    cp "$src" "$dst"
    echo "created: ${dst#"$SYCL_DIR"/}"
  fi
}

# config.json (runner + toolchain) lives at .sycl/config.json
copy_if_absent "$TEMPLATES/config.json"        "$SYCL_DIR/config.json"
# structured state
copy_if_absent "$TEMPLATES/project.json"       "$STATE/project.json"
copy_if_absent "$TEMPLATES/kernel-index.json"  "$STATE/kernels/index.json"
# analytics rollup (efficiency & cost); regenerated by metrics.sh, seeded here so the
# dashboard/report always have a file to read.
copy_if_absent "$TEMPLATES/metrics.json"       "$STATE/metrics.json"

# Stamp project name + timestamp into a freshly created project.json (best-effort, no jq dep).
if grep -q '"name": "REPLACE_ME"' "$STATE/project.json" 2>/dev/null; then
  sed -i.bak \
    -e "s/\"name\": \"REPLACE_ME\"/\"name\": \"${PROJECT_NAME//\//\\/}\"/" \
    -e "s/\"updated_at\": \"1970-01-01T00:00:00Z\"/\"updated_at\": \"${now}\"/" \
    "$STATE/project.json" && rm -f "$STATE/project.json.bak"
  echo "stamped project name: $PROJECT_NAME"
fi

# Generate the initial PROGRESS.md view.
bash "$SCRIPT_DIR/gen-progress.sh" >/dev/null 2>&1 || true

echo "State initialized under: $SYCL_DIR"
